### ISSUE TITLE
The code in `py-udf-hl.c` does not seem to be NumPy 2 compatible

### ISSUE THREAD

**Issue by pjonsson** [davidfrantz/force#428]
Discovered this while trying to update to GDAL 3.13, whose Docker image contains NumPy 2.3.5 (https://github.com/davidfrantz/base_image/pull/23).

The code in `py-udf-hl.c` does not seem to be NumPy 2 compatible:
```
#15 5.020 src/modules/higher-level/py-udf-hl.c: In function 'py_dimlab_t python_label_dimensions(ard_t*, tsa_t*, int, char*, int, int, int, par_udf_t*)':
#15 5.020 src/modules/higher-level/py-udf-hl.c:387:22: error: 'PyArray_Descr' {aka 'struct _PyArray_Descr'} has no member named 'elsize'
#15 5.020   387 |   pylab.desc_sensor->elsize = NPOW_10;
#15 5.020       |                      ^~~~~~
#15 5.020 src/modules/higher-level/py-udf-hl.c:391:24: error: 'PyArray_Descr' {aka 'struct _PyArray_Descr'} has no member named 'elsize'
#15 5.020   391 |   pylab.desc_bandname->elsize = NPOW_10;
#15 5.020       |                        ^~~~~~
#15 5.023 make: *** [build/higher-level.mk:87: py-udf-hl] Error 1
```
I don't want to look at the C code of FORCE, but based on the compilation error I'm guessing the NumPy 2 migration notes here are relevant for this particular issue: https://numpy.org/doc/2.0/release/2.0.0-notes.html#descriptor-elsize-and-alignment-access

**Comment by davidfrantz** [comment]
The last 5 commits in develop fix the compilation errors caused by the new versions in https://github.com/davidfrantz/base_image/pull/23

- elsize compile errors (numpy 2)
- CSLConstList compile errors (GDAL 3.11.3)
- a general compiler warning in GCC 15.2

This is confirmed to work on my local setup, so backward compatibility seems to be given.

However, running FORCE still does not work in this base image:
https://github.com/davidfrantz/base_image/pull/23

- R packages copied from incorrect directory (it bothers me that the path constantly changes), so no packages in image
- I still get execution error when running Python UDFs. I have to investigate this further....

**Comment by pjonsson** [comment]
> * R packages copied from incorrect directory (it bothers me that the path constantly changes), so no packages in image

Sorry, I've updated the PR, so `R -e 'lapply(.libPaths(), list.files)'` now lists a bunch of packages again.

> The last 5 commits in develop fix the compilation errors caused by the new versions in [davidfrantz/base_image#23](https://github.com/davidfrantz/base_image/pull/23)

Sweet, closing this as completed since I'm guessing Python UDFs not working in GDAL 3.13 is related to changes in Python 3.14, not NumPy 2.x.

I have experienced that the garbage collector in Python 3.14.4 is less eager to collect things than it was in Python 3.12, so maybe something isn't getting garbage collected for UDFs as soon as it used to?

They are reverting to the previous garbage collector in Python 3.14.5. I'm not sure if Ubuntu 26.04 will get that Python patch release or if Ubuntu will maintain a 3.14.4 for the next 5 years.
