### PR TITLE
small fix to make this work with opencv-3.4.1 under centos8 newest ub…

### PR DESCRIPTION
**Pull request by kemnitzs**
…untu version is 3.2 which still seems to work

### CODE REVIEW

**Comment by kemnitzs** [comment]
the error from gcc-9.2.0:

``
src/aux-level/train-aux.cpp:47:12: error: could not convert ‘0’ from ‘long int’ to ‘cv::Ptr<cv::ml::StatModel>’
   47 |     return NULL;
      |            ^~~~
      |            |
      |            long int
make: *** [Makefile:309: train_aux] Error 1
`` 
Meaning that the NULL macro 0 can not be converted to the cv::Ptr<T> from reading the documentation (https://docs.opencv.org/3.4/d0/de7/structcv_1_1Ptr.html#a85cbac0b7613df0999cea5b6250e7851) I would say that it should work, but it dosen't.

Documentation says, that calling the default constructor should result in the same thing.

``
cv::Ptr< T >::Ptr	(		)	
The default constructor creates a null Ptr 
``
